---
- name: Configure Kubernetes/Docker Baseline
  hosts: all
  become: yes
  vars:
    containerd_version: "1.7.*"
    k8s_version: "1.29.*"
    sysctl_params:
      # Networking
      net.bridge.bridge-nf-call-ip6tables: 1
      net.bridge.bridge-nf-call-iptables: 1
      net.ipv4.ip_forward: 1
      net.core.somaxconn: 8192
      net.ipv4.tcp_tw_reuse: 1

      # Security
      kernel.kptr_restrict: 2
      vm.swappiness: 10

      # Monitoring/Performance
      fs.inotify.max_user_watches: 524288
      fs.file-max: 2097152
      net.core.netdev_max_backlog: 16384

  tasks:
    # Phase 1: System Preparation
    - name: Verify baseline hardware
      assert:
        that:
          - ansible_processor_vcpus >= 2
          - ansible_memtotal_mb >= 2048
          - ansible_distribution in ['Ubuntu', 'Debian']
        msg: "Minimum system requirements not met"

    - name: Install essential packages
      apt:
        name:
          - curl
          - awscli
          - gnupg2
          - software-properties-common
          - apt-transport-https
          - ca-certificates
          - jq
          - openssl
          - libssl-dev
          - nfs-common
          - conntrack
        state: present
        update_cache: yes
        retries: 3
        delay: 10

    # Phase 2: Containerd Setup
    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker-ce-stable

    - name: Install containerd runtime
      apt:
        name: "containerd.io={{ containerd_version }}"
        state: present
        force: yes

    - name: Configure containerd defaults
      copy:
        dest: /etc/containerd/config.toml
        content: |
          version = 2
          [plugins."io.containerd.grpc.v1.cri"]
            systemd_cgroup = true
            sandbox_image = "registry.k8s.io/pause:3.9"
          [plugins."io.containerd.grpc.v1.cri".containerd]
            snapshotter = "overlayfs"
            disable_snapshot_annotations = false
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
              SystemdCgroup = true
              Root = "/var/lib/containerd/runc"
              runtime_type = "io.containerd.runc.v2"
              runtime_engine = "/usr/bin/runc"
              privileged_without_host_devices = false
      notify: restart containerd

    # Phase 3: Kernel Optimization
    - name: Load required kernel modules
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter
        - ip_vs
        - ip_vs_rr
        - ip_vs_sh
        - nf_conntrack

    - name: Apply cluster-wide kernel parameters
      sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        sysctl_set: yes
        reload: yes
      loop: "{{ sysctl_params | dict2items }}"
      notify: restart kubelet
      tags: [security, kernel]

    # Phase 4: Kubernetes Base Installation
    - name: Add Kubernetes repo
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ k8s_version.split('.')[0] }}/deb/ /"
        state: present
        filename: kubernetes-stable

    - name: Pin k8s package versions
      apt_preferences:
        filename: k8s-pin
        package: "*"
        pin: "version {{ k8s_version }}-*"
        pin_priority: 1000

    - name: Install kube components
      apt:
        name:
          - kubelet={{ k8s_version }}
          - kubeadm={{ k8s_version }}
          - kubectl={{ k8s_version }}
        state: present
        install_recommends: no

    - name: Lock package versions
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl

    # Phase 5: System Configuration
    - name: Configure kubelet defaults
      copy:
        dest: /etc/default/kubelet
        content: |
          KUBELET_EXTRA_ARGS="--node-ip=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4) \
            --protect-kernel-defaults=true \
            --enforce-node-allocatable=pods \
            --read-only-port=0 \
            --event-qps=0"
          KUBELET_CGROUP_ARGS="--cgroup-driver=systemd"
      notify: restart kubelet

    - name: Install AppArmor utilities
      apt:
        name: apparmor-utils
        state: present

    - name: Load AppArmor profiles
      command: apparmor_parser -r -W /etc/apparmor.d/*
      when: ansible_distribution in ['Ubuntu', 'Debian']

    - name: Create PKI directory
      file:
        path: /etc/kubernetes/pki
        state: directory
        mode: 0700

  handlers:
    - name: restart containerd
      systemd:
        name: containerd
        state: restarted
        enabled: yes

    - name: restart kubelet
      systemd:
        name: kubelet
        state: restarted
        enabled: yes
