- name: Reload ingress-nginx
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx
    namespace: ingress-nginx
    release_values:
      controller:
        extraArgs:
          enable-ssl-passthrough: "true"
  when: "'ingress-nginx' in installed_charts.stdout"

- name: Restart api-server
  kubernetes.core.k8s:
    resource: pod
    namespace: kube-system
    name: "{{ item.metadata.name }}"
    state: restarted
  loop: "{{ kube_apiserver_pods.resources }}"
  when: kube_apiserver_pods.resources | length > 0
